### ISSUE TITLE
Fix visually-hidden and visually-hidden--focusable mixings

### ISSUE THREAD

**Issue by Eduruiz** [robsonsobral/initial-css#105]
I think I found that the `visually-hidden` mixing is actually focusable, making the `--focusable` one redundant.  
I made a [test case here](https://codepen.io/eduruiz/pen/NWgPPOw) where you can see the focus changing from the github to the google link even with the link being visually hidden.  
adding `visibility: hidden;` fix it, but I'm not sure if it breaks something else.

**Comment by robsonsobral** [comment]
As we don't need to be backward compatible, we can "fix" it.

(I've a huuuuuuuuuuuuuuuuuuuge amount of improvements to release)
