### ISSUE TITLE
Missing rule on cssComb

### ISSUE THREAD

**Issue by robsonsobral** [robsonsobral/initial-css#57]
**[Original report](https://bitbucket.org/sobral/initial-css/issue/57) by sobral (Bitbucket: [sobral](https://bitbucket.org/sobral), GitHub: [robsonsobral](https://github.com/robsonsobral)).**

----------------------------------------

`"space-before-combinator": " ",`

**Comment by Eduruiz** [comment]
Closing this since cssComb will be replaced with [stylelint order](https://github.com/hudochenkov/stylelint-order)
